Remove pip update in packer build
Remove pip update in packer/scripts/infrasim-compute.sh.
There is some import issue with latest pip 10.0.0
Error message: 'ImportError: cannot import name main'